name: build
concurrency:
    group: build-${{ github.ref }}
    cancel-in-progress: true
on: 
    push:
        paths-ignore:
        - '**/*.md'    
    workflow_dispatch:
jobs:
    build-python:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.10', '3.11', '3.12']
        name: Python ${{ matrix.python-version }}
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install --requirement requirements.txt
                pip install jupyter
            - run: cd src/chapters; jupyter nbconvert --to python chap01.ipynb; ipython chap01.py
            - run: cd src/chapters; jupyter nbconvert --to python chap02.ipynb; ipython chap02.py
            - run: cd src/chapters; jupyter nbconvert --to python --execute chap03.ipynb
            - run: cd src/chapters; jupyter nbconvert --to python chap04.ipynb; ipython chap04.py
            - run: cd src/chapters; jupyter nbconvert --to python chap05.ipynb; ipython chap05.py
            - run: cd src/chapters; jupyter nbconvert --to python chap06.ipynb; ipython chap06.py
            - run: cd src/chapters; jupyter nbconvert --to python chap07.ipynb; ipython chap07.py
            - run: cd src/chapters; jupyter nbconvert --to python chap08.ipynb; ipython chap08.py
            - run: cd src/chapters; jupyter nbconvert --to python chap09.ipynb; ipython chap09.py
            - run: cd src/chapters; jupyter nbconvert --to python chap10.ipynb; ipython chap10.py
            - run: cd src/chapters; jupyter nbconvert --to python chap11.ipynb; ipython chap11.py
            - run: cd src/chapters; jupyter nbconvert --to python chap12.ipynb; ipython chap12.py
            - run: cd src/chapters; jupyter nbconvert --to python chap13.ipynb; ipython chap13.py
            - run: cd src/chapters; jupyter nbconvert --to python chap14.ipynb; ipython chap14.py
            - run: cd src/chapters; jupyter nbconvert --to python chap15.ipynb; ipython chap15.py
            - run: cd src/chapters; jupyter nbconvert --to python chap16.ipynb; ipython chap16.py
            - run: cd src/chapters; jupyter nbconvert --to python chap17.ipynb; ipython chap17.py
            - run: cd src/chapters; jupyter nbconvert --to python chap18.ipynb; ipython chap18.py
            - run: cd src/chapters; jupyter nbconvert --to python chap19.ipynb; ipython chap19.py
            - run: cd src/chapters; jupyter nbconvert --to python chap20.ipynb; ipython chap20.py
            - run: cd src/chapters; jupyter nbconvert --to python chap21.ipynb; ipython chap21.py
            - run: cd src/chapters; jupyter nbconvert --to python chap22.ipynb; ipython chap22.py
            - run: cd src/chapters; jupyter nbconvert --to python chap23.ipynb; ipython chap23.py

