name: build
concurrency:
    group: build-${{ github.ref }}
    cancel-in-progress: true
on: 
    push:
        paths-ignore:
        - '**/*.md'    
    workflow_dispatch:
jobs:
    build-python:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
        name: Python ${{ matrix.python-version }}
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install --requirement requirements.txt
            - run: cd src/chapters; jupyter nbconvert --execute chap01.ipynb
            - run: cd src/chapters; jupyter nbconvert --execute chap02.ipynb
            - run: cd src/chapters; jupyter nbconvert --execute chap03.ipynb
            - run: cd src/chapters; jupyter nbconvert --execute chap04.ipynb
