name: build
concurrency:
    group: build-${{ github.ref }}
    cancel-in-progress: true
on: 
    push:
        paths-ignore:
        - '**/*.md'    
    workflow_dispatch:
jobs:
    build-python:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.10', '3.11', '3.12']
        name: Python ${{ matrix.python-version }}
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install --requirement requirements.txt
                pip install jupyter
            - run: cd src/chapters; jupyter nbconvert --to python chap01.ipynb; python chap01.py
            - run: cd src/chapters; jupyter nbconvert --to python chap02.ipynb; python chap02.py
            - run: cd src/chapters; jupyter nbconvert --to python chap03.ipynb; python chap03.py
            - run: cd src/chapters; jupyter nbconvert --to python chap04.ipynb; python chap04.py
